[project]
name = "mcp-dalle-server"
version = "0.1.0"
description = "MCP server for generating images using DALL-E based on prompts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
]
